"use client";

import { useMemo, useState } from "react";
import { pupils, recentEvidence } from "../lib/demo";

type View = "home" | "class" | "capture" | "portfolio" | "evidence";
const tags = ["Basketball", "Football", "Swimming", "Skill", "Decision Making", "Teamwork", "Leadership", "KNOW", "SHOW", "GROW"];

export default function Sportfolio() {
  const [view, setView] = useState<View>("home");
  const [selected, setSelected] = useState<string[]>([]);
  const [tagged, setTagged] = useState<string[]>(["Basketball", "Decision Making", "SHOW"]);
  const [saved, setSaved] = useState(false);
  const [query, setQuery] = useState("");
  const chosen = pupils.filter(p => selected.includes(p.id));
  const visiblePupils = useMemo(() => pupils.filter(p => p.name.toLowerCase().includes(query.toLowerCase())), [query]);
  const selectPupil = (id: string) => setSelected(s => s.includes(id) ? s.filter(x => x !== id) : [...s, id]);
  const selectTag = (tag: string) => setTagged(t => t.includes(tag) ? t.filter(x => x !== tag) : [...t, tag]);
  const goCapture = () => { setSaved(false); setView("capture"); };

  return <main className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="mark">S</div><span>SPORTFOLIO</span></div>
      <nav>
        <button className={view === "home" ? "active" : ""} onClick={() => setView("home")}>⌂ <span>Home</span></button>
        <button className={view === "class" ? "active" : ""} onClick={() => setView("class")}>◫ <span>Classes</span></button>
        <button className={view === "capture" ? "active" : ""} onClick={goCapture}>◉ <span>Capture</span></button>
        <button onClick={() => setView("class")}>⌕ <span>Pupils</span></button>
        <button onClick={() => setView("evidence")}>▧ <span>Evidence</span></button>
      </nav>
      <div className="sidebar-bottom"><div className="avatar small">TS</div><div><strong>Toby Sumerfield</strong><small>HIBA Academy</small></div></div>
    </aside>
    <section className="content">
      <header><div className="crumb">HIBA ACADEMY <span>/</span> {view === "capture" ? "QUICK CAPTURE" : "2026–27"}</div><div className="header-actions"><button className="icon-button">?</button><div className="avatar">TS</div></div></header>
      {view === "home" && <Home goCapture={goCapture} openClass={() => setView("class")} openEvidence={() => setView("evidence")} />}
      {view === "class" && <ClassView pupils={visiblePupils} query={query} setQuery={setQuery} onCapture={goCapture} onPortfolio={() => setView("portfolio")} />}
      {view === "capture" && <Capture selected={selected} chosen={chosen} tagged={tagged} selectPupil={selectPupil} selectTag={selectTag} saved={saved} save={() => setSaved(true)} />}
      {view === "portfolio" && <Portfolio onBack={() => setView("class")} onEvidence={() => setView("evidence")} />}
      {view === "evidence" && <Evidence onBack={() => setView("home")} />}
    </section>
    <nav className="mobile-nav"><button onClick={() => setView("home")}>⌂<span>Home</span></button><button onClick={() => setView("class")}>◫<span>Classes</span></button><button className="capture-mobile" onClick={goCapture}>◉<span>Capture</span></button><button onClick={() => setView("class")}>⌕<span>Pupils</span></button></nav>
  </main>;
}

function Home({ goCapture, openClass, openEvidence }: { goCapture: () => void; openClass: () => void; openEvidence: () => void }) {
  return <div className="page"><div className="intro-row"><div><h1>Good morning, Toby.</h1><p>Make today’s learning visible.</p></div><button className="primary" onClick={goCapture}>◉ Quick capture</button></div><section className="today"><div className="eyebrow">TODAY · THURSDAY 28 AUGUST</div><div className="schedule"><div className="time">09:20</div><div className="schedule-line"></div><div><strong>Grade 5A</strong><p>Basketball · Passing & decision making</p></div><button onClick={goCapture}>Capture</button></div><div className="schedule"><div className="time">11:10</div><div className="schedule-line muted"></div><div><strong>Grade 6A</strong><p>Swimming · Technique</p></div><button onClick={goCapture}>Capture</button></div></section><section className="split"><div><div className="section-heading"><div><div className="eyebrow">KEEP AN EYE ON</div><h2>Evidence coverage</h2></div><button className="text-button" onClick={openClass}>Open Grade 5A →</button></div><div className="coverage"><div className="coverage-num">20<span>/24</span></div><div><strong>Pupils observed this unit</strong><p>Four pupils have not yet had evidence captured.</p><div className="bar"><span></span></div></div></div><div className="pupil-pills">{pupils.slice(3, 7).map(p => <div key={p.id} className="pupil-pill"><div className="avatar" style={{background:p.colour}}>{p.initials}</div>{p.name}</div>)}</div></div><div className="reflection-card"><div className="eyebrow">REFLECTIONS</div><div className="reflection-count">3</div><strong>Awaiting your review</strong><p>Your pupils have responded to a reflection request.</p><button className="dark-button" onClick={openEvidence}>Review reflections</button></div></section><section><div className="section-heading"><div><div className="eyebrow">RECENTLY CAPTURED</div><h2>Keep the story going</h2></div><button className="text-button" onClick={openEvidence}>All evidence →</button></div><div className="evidence-grid">{recentEvidence.map((e,i)=><article className="evidence-card" key={e.title} onClick={openEvidence}><div className={'evidence-image '+e.image}><span>{i===0 ? '▶' : '●'}</span></div><div className="evidence-body"><div className="tag-row">{e.tags.map(t=><span key={t}>{t}</span>)}</div><h3>{e.title}</h3><p>{e.pupils} · {e.time}</p></div></article>)}</div></section></div>;
}

function ClassView({ pupils: items, query, setQuery, onCapture, onPortfolio }: { pupils: typeof pupils; query: string; setQuery: (v:string)=>void; onCapture:()=>void; onPortfolio:()=>void }) { return <div className="page"><div className="page-top"><div><button className="back">‹ Classes</button><h1>Grade 5A</h1><p>Basketball · 24 pupils · 2026–27</p></div><button className="primary" onClick={onCapture}>◉ Capture for Grade 5A</button></div><div className="filter-row"><input aria-label="Search pupils" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pupils"/><button className="filter active-filter">All <b>24</b></button><button className="filter">Needs evidence <b>4</b></button><button className="filter">Reflection due <b>3</b></button></div><div className="pupil-grid">{items.map(p=><button className="pupil-card" key={p.id} onClick={onPortfolio}><div className="avatar large" style={{background:p.colour}}>{p.initials}</div><div className="pupil-card-info"><h3>{p.name}</h3><p>{p.evidence} pieces · Last: {p.lastSeen}</p><div className="status-row">{p.reflection === "Due" && <span className="status due">Reflection due</span>}{p.reflection === "Reviewed" && <span className="status reviewed">Reviewed</span>}<span className="goal-dot">◎ {p.goal}</span></div></div><span className="arrow">›</span></button>)}</div></div> }

function Capture({ selected, chosen, tagged, selectPupil, selectTag, saved, save }: { selected:string[]; chosen: typeof pupils; tagged:string[]; selectPupil:(id:string)=>void; selectTag:(tag:string)=>void; saved:boolean; save:()=>void }) { return <div className="capture-page"><div className="capture-head"><div><button className="back">‹ Grade 5A</button><h1>Quick capture</h1></div><div className="capture-step"><span className="step done">1</span><i></i><span className="step active">2</span><i></i><span className="step">3</span></div></div><div className="capture-layout"><div className="capture-stage"><div className="capture-video"><div className="recording"><span></span> RECORDING</div><div className="play-circle">▮▮</div><div className="rec-time">00:12</div></div><div className="capture-controls"><button className="mode-button">⌁ Photo</button><button className="record-button"><span></span></button><button className="mode-button active-mode">▣ Video</button></div><p className="capture-hint">12-second clip ready. Select pupils and tags to save it.</p></div><aside className="capture-panel"><div className="panel-section"><div className="panel-title"><h3>Who is this evidence for?</h3><span>{selected.length} selected</span></div><div className="quick-grid">{pupils.map(p=><button key={p.id} onClick={()=>selectPupil(p.id)} className={selected.includes(p.id)?"person selected":"person"}><div className="avatar" style={{background:p.colour}}>{p.initials}</div><span>{p.name.split(" ")[0]}</span>{selected.includes(p.id)&&<b>✓</b>}</button>)}</div></div><div className="panel-section"><div className="panel-title"><h3>What does it show?</h3><span>Tap to tag</span></div><div className="tap-tags">{tags.map(t=><button key={t} onClick={()=>selectTag(t)} className={tagged.includes(t)?"selected-tag":""}>{t}</button>)}</div></div><div className="selected-summary">{chosen.length ? <><div className="mini-avatars">{chosen.map(p=><div className="avatar" style={{background:p.colour}} key={p.id}>{p.initials}</div>)}</div><strong>{chosen.length} pupil{chosen.length>1?"s":""} will receive this</strong></> : <span>Select pupils to attach this evidence.</span>}</div><button disabled={!selected.length} className="save-capture" onClick={save}>{saved ? "✓ Saved to Sportfolios" : "Save evidence"}</button>{saved && <button className="request">Request reflection from {selected.length} pupil{selected.length>1?"s":""}</button>}</aside></div></div> }

function Portfolio({ onBack, onEvidence }: {onBack:()=>void;onEvidence:()=>void}) { const p=pupils[0]; return <div className="page"><button className="back" onClick={onBack}>‹ Grade 5A</button><div className="portfolio-header"><div className="avatar profile" style={{background:p.colour}}>{p.initials}</div><div><h1>Mia Chen</h1><p>Grade 5A · U13 Basketball</p><div className="goal-banner">◎ Current goal: <strong>Scan before receiving so I can see my options.</strong></div></div><button className="outline">Request reflection</button></div><div className="tabs"><button className="tab selected-tab">Portfolio</button><button className="tab">Progress</button><button className="tab">Goals</button><button className="tab">Reflections</button></div><div className="timeline"><article className="timeline-item" onClick={onEvidence}><div className="evidence-image court tall"><span>▶</span></div><div className="timeline-copy"><div className="tag-row"><span>Basketball</span><span>Decision Making</span><span>SHOW</span></div><h2>Making the fast-break decision</h2><p className="muted-text">Today · Grade 5A · Toby Sumerfield</p><p>Excellent awareness of the space ahead. You spotted Ava early and moved the ball forward quickly.</p><div className="student-reflection"><strong>Mia reflected</strong><p>“I looked up before I got the ball. I could see Ava running into space, so I passed it earlier.”</p></div></div></article><article className="timeline-item"><div className="evidence-image field tall"><span>●</span></div><div className="timeline-copy"><div className="tag-row"><span>Teamwork</span><span>GROW</span></div><h2>Supporting teammates</h2><p className="muted-text">14 August · Grade 5A</p></div></article></div></div> }

function Evidence({onBack}:{onBack:()=>void}) { return <div className="evidence-page"><button className="back" onClick={onBack}>‹ Back</button><div className="evidence-detail"><div className="detail-media court"><div className="play-big">▶</div></div><div className="detail-copy"><div className="tag-row"><span>Basketball</span><span>Decision Making</span><span>SHOW</span></div><h1>Making the fast-break decision</h1><p className="muted-text">Today · Grade 5A · Toby Sumerfield</p><div className="shared-with"><div className="mini-avatars">{pupils.slice(0,4).map(p=><div key={p.id} className="avatar" style={{background:p.colour}}>{p.initials}</div>)}</div><span>Shared with 4 pupils</span></div><hr/><h3>Teacher feedback</h3><p>Excellent awareness of the space ahead. You spotted Ava early and moved the ball forward quickly.</p><div className="student-reflection large-reflection"><div><strong>Mia Chen reflected</strong><span className="status reviewed">Reviewed</span></div><p>“I looked up before I got the ball. I could see Ava running into space, so I passed it earlier. Next time I will call out before I receive it.”</p><button className="audio">▶ Listen to voice reflection <span>0:18</span></button></div></div></div></div> }
