-- Sportfolio V1. Apply only to a dedicated Supabase project after safeguarding review.
create type public.app_role as enum ('school_admin', 'teacher', 'student', 'parent');
create type public.item_visibility as enum ('private', 'student_visible', 'parent_visible');
create type public.goal_status as enum ('not_started', 'working_on_it', 'achieved');

create table public.schools (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, school_id uuid not null references public.schools(id) on delete restrict, role public.app_role not null, display_name text not null, avatar_path text, created_at timestamptz not null default now());
create table public.students (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, profile_id uuid unique references public.profiles(id) on delete set null, external_ref text, first_name text not null, last_name text not null, grade text, archived_at timestamptz, created_at timestamptz not null default now(), unique(school_id, external_ref));
create table public.classes (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, academic_year text not null, grade text, activity text, curriculum text, archived_at timestamptz, created_at timestamptz not null default now());
create table public.class_teachers (class_id uuid not null references public.classes(id) on delete cascade, teacher_id uuid not null references public.profiles(id) on delete cascade, primary key(class_id, teacher_id));
create table public.class_memberships (class_id uuid not null references public.classes(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, joined_at timestamptz not null default now(), left_at timestamptz, primary key(class_id, student_id));
create table public.activities (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, active boolean not null default true, unique(school_id, name));
create table public.tags (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, name text not null, category text not null check (category in ('activity','evidence_type','dimension','performance','custom')), colour text, active boolean not null default true, unique(school_id, name, category));
create table public.portfolio_items (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, class_id uuid references public.classes(id) on delete set null, author_id uuid not null references public.profiles(id) on delete restrict, activity_id uuid references public.activities(id) on delete set null, title text, teacher_note text, occurred_at timestamptz not null default now(), visibility public.item_visibility not null default 'private', created_at timestamptz not null default now());
create table public.portfolio_item_students (portfolio_item_id uuid not null references public.portfolio_items(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, primary key(portfolio_item_id, student_id));
create table public.media (id uuid primary key default gen_random_uuid(), portfolio_item_id uuid not null references public.portfolio_items(id) on delete cascade, bucket_path text not null unique, media_type text not null check(media_type in ('image','video','audio')), duration_seconds integer, created_at timestamptz not null default now());
create table public.portfolio_item_tags (portfolio_item_id uuid not null references public.portfolio_items(id) on delete cascade, tag_id uuid not null references public.tags(id) on delete restrict, primary key(portfolio_item_id, tag_id));
create table public.reflections (id uuid primary key default gen_random_uuid(), portfolio_item_id uuid not null references public.portfolio_items(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, prompt text, text_response text, voice_path text, requested_at timestamptz not null default now(), submitted_at timestamptz, reviewed_at timestamptz, reviewed_by uuid references public.profiles(id) on delete set null, unique(portfolio_item_id, student_id));
create table public.comments (id uuid primary key default gen_random_uuid(), portfolio_item_id uuid not null references public.portfolio_items(id) on delete cascade, author_id uuid not null references public.profiles(id) on delete restrict, body text not null, created_at timestamptz not null default now());
create table public.voice_notes (id uuid primary key default gen_random_uuid(), portfolio_item_id uuid not null references public.portfolio_items(id) on delete cascade, author_id uuid not null references public.profiles(id) on delete restrict, bucket_path text not null unique, duration_seconds integer, created_at timestamptz not null default now());
create table public.goals (id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, activity_id uuid references public.activities(id) on delete set null, body text not null, target_date date, status public.goal_status not null default 'not_started', created_at timestamptz not null default now());
create table public.goal_evidence (goal_id uuid not null references public.goals(id) on delete cascade, portfolio_item_id uuid not null references public.portfolio_items(id) on delete cascade, primary key(goal_id, portfolio_item_id));
create table public.audit_log (id bigint generated always as identity primary key, school_id uuid not null references public.schools(id) on delete cascade, actor_id uuid references public.profiles(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, created_at timestamptz not null default now());

alter table public.schools enable row level security; alter table public.profiles enable row level security; alter table public.students enable row level security; alter table public.classes enable row level security; alter table public.class_teachers enable row level security; alter table public.class_memberships enable row level security; alter table public.activities enable row level security; alter table public.tags enable row level security; alter table public.portfolio_items enable row level security; alter table public.portfolio_item_students enable row level security; alter table public.media enable row level security; alter table public.portfolio_item_tags enable row level security; alter table public.reflections enable row level security; alter table public.comments enable row level security; alter table public.voice_notes enable row level security; alter table public.goals enable row level security; alter table public.goal_evidence enable row level security; alter table public.audit_log enable row level security;

-- Policies are intentionally added only after the final identity and parent-access design is agreed.
-- Do not grant anon/authenticated access or create permissive policies as a shortcut.
